### ISSUE TITLE
Need more diverse seeds

### ISSUE THREAD

**Issue by sunpenglv** [SoftSec-KAIST/CodeAlchemist#2]
HI. When i use CodeAlchemist, it tells me "Need more diverse seeds", how many seeds is enough atl least?

**Comment by DaramG** [comment]
To handle the exception in issue #1, CodeAlchemist gracefully exit with"Need more diverse seeds".
Please see the issue #1.

**Comment by sunpenglv** [comment]
HI

I did what #1 said.

rm -rf /home/test/Desktop/path/preproc
mkdir /home/test/Desktop/path/preproc

and used the command:
dotnet bin/Main.dll rewrite /home/test/Desktop/path/conf/Chakra.conf

and it said:
[INFO] BuiltIns:
[| globalThis, NaN, Infinity, undefined, eval, parseInt, parseFloat, isNaN, isFinite, decodeURI, decodeURIComponent, encodeURI, encodeURIComponent, escape, unescape, Object, Array, Boolean, Symbol, Proxy, Reflect, Promise, Date, Function, Math, Number, String, RegExp, ArrayBuffer, DataView, Int8Array, Uint8Array, Uint8ClampedArray, Int16Array, Uint16Array, Int32Array, Uint32Array, Float32Array, Float64Array, JSON, Intl, Map, Set, WeakMap, WeakSet, Error, EvalError, RangeError, ReferenceError, SyntaxError, TypeError, URIError, WebAssembly, WScript, print, read, readbuffer, readline, console |]

Unhandled Exception: System.ComponentModel.Win32Exception: No such file or directory
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Common.Executor.execNodeJs(String js, String argv) in /home/sunpeng/CodeAlchemist/src/Common/Executor.fs:line 39
   at Main.Preprocess.parseSeed(Conf conf) in /home/sunpeng/CodeAlchemist/src/Main/Preprocess.fs:line 15
   at Main.Run.main(String[] argv) in /home/test/Desktop/path/src/Main/Main.fs:line 84
Aborted

and i did it again:
dotnet bin/Main.dll rewrite /home/test/Desktop/path/conf/Chakra.conf

it worked right:
[| globalThis, NaN, Infinity, undefined, eval, parseInt, parseFloat, isNaN, isFinite, decodeURI, decodeURIComponent, encodeURI, encodeURIComponent, escape, unescape, Object, Array, Boolean, Symbol, Proxy, Reflect, Promise, Date, Function, Math, Number, String, RegExp, ArrayBuffer, DataView, Int8Array, Uint8Array, Uint8ClampedArray, Int16Array, Uint16Array, Int32Array, Uint32Array, Float32Array, Float64Array, JSON, Intl, Map, Set, WeakMap, WeakSet, Error, EvalError, RangeError, ReferenceError, SyntaxError, TypeError, URIError, WebAssembly, WScript, print, read, readbuffer, readline, console |]

continue i used:
dotnet bin/Main.dll instrument /home/test/Desktop/path/conf/Chakra.conf

it worked alse right:
[INFO] BuiltIns:
[| globalThis, NaN, Infinity, undefined, eval, parseInt, parseFloat, isNaN, isFinite, decodeURI, decodeURIComponent, encodeURI, encodeURIComponent, escape, unescape, Object, Array, Boolean, Symbol, Proxy, Reflect, Promise, Date, Function, Math, Number, String, RegExp, ArrayBuffer, DataView, Int8Array, Uint8Array, Uint8ClampedArray, Int16Array, Uint16Array, Int32Array, Uint32Array, Float32Array, Float64Array, JSON, Intl, Map, Set, WeakMap, WeakSet, Error, EvalError, RangeError, ReferenceError, SyntaxError, TypeError, URIError, WebAssembly, WScript, print, read, readbuffer, readline, console |]

but there was no script generated and finally i used:
dotnet bin/Main.dll fuzz  /home/test/Desktop/path/conf/Chakra.conf

it showed:
[INFO] BuiltIns:
[| globalThis, NaN, Infinity, undefined, eval, parseInt, parseFloat, isNaN, isFinite, decodeURI, decodeURIComponent, encodeURI, encodeURIComponent, escape, unescape, Object, Array, Boolean, Symbol, Proxy, Reflect, Promise, Date, Function, Math, Number, String, RegExp, ArrayBuffer, DataView, Int8Array, Uint8Array, Uint8ClampedArray, Int16Array, Uint16Array, Int32Array, Uint32Array, Float32Array, Float64Array, JSON, Intl, Map, Set, WeakMap, WeakSet, Error, EvalError, RangeError, ReferenceError, SyntaxError, TypeError, URIError, WebAssembly, WScript, print, read, readbuffer, readline, console |]
[ERROR] Need more diverse seeds

could you help me?

**Comment by DaramG** [comment]
I think your system does not have `node`.
You should follow installation guide in [README.md](../blob/master/README.md).

**Comment by sunpenglv** [comment]
> I think your system does not have `node`.
> You should follow installation guide in [README.md](../blob/master/README.md).

following is my nodejs node npm version:
nodejs -v
v8.16.0

node -v
v8.16.0

npm -v
6.9.0

and the script is not generated anyway..

**Comment by DaramG** [comment]
If `preporc/json` directory exists, CodeAlchemist assumes that parsing result is already in `preproc/json`.
So, can you execute again after removing `preproc/json`?

If it does not create any file in `preproc/json`, `node` with `esprima` does not work and we may need another action to resolve this issue.

**Comment by sunpenglv** [comment]
> If `preporc/json` directory exists, CodeAlchemist assumes that parsing result is already in `preproc/json`.
> So, can you execute again after removing `preproc/json`?
> 
> If it does not create any file in `preproc/json`, `node` with `esprima` does not work and we may need another action to resolve this issue.

I rm preproc/json and it works, thank you very much :)
