### ISSUE TITLE
Error: Need more diverse seeds

### ISSUE THREAD

**Issue by MrSynAckSter-zz** [SoftSec-KAIST/CodeAlchemist#4]
Hello!

Your paper makes it a little unclear as to what the intended corpus of seeds must look like. I took a guess and used the ECMAScript conformance test suite but got the error:

[ERROR] Need more diverse seeds

Can you give some suggestions of what a valid suite of seed javascript files should look like?

**Comment by DaramG** [comment]
If there is no code brick, which has an empty pre-condition, CodeAlchemist will exit with that error message. And CodeAlchemist only can use a part of seeds, which do not raise any errors.
So, you should add more seeds including code bricks, which has an empty pre-condition, and make sure that they do not raise errors.

**Comment by MrSynAckSter-zz** [comment]
are there any pre-existing Javascript code bases that would recommend or should I focus on making something entirely from scratch?

**Comment by DaramG** [comment]
There are bunch of test JS code snippets in each JS engine repositories.
They will be helpful to construct JS seeds.

**Comment by zjuchenyuan** [comment]
@DaramG Could you provide specific commands for construct usable js seeds?

I have tried `stress` and `test262`, both leading to this error `Error: Need more diverse seeds`.
