### ISSUE TITLE
How to build chakracore

### ISSUE THREAD

**Issue by whiteHat001** [SoftSec-KAIST/CodeAlchemist#5]
I build witth options "./build.sh --sanitize=address --static"
Is it right?

**Comment by xcainiao** [comment]
差不多 
就这样
./build.sh --sanitize=address --cxx=/usr/bin/clang++ --cc=/usr/bin/clang --static -j 4

**Comment by whiteHat001** [comment]
> 差不多
> 就这样
> ./build.sh --sanitize=address --cxx=/usr/bin/clang++ --cc=/usr/bin/clang --static -j 4

不行的，他这个工具有很多误报。

**Comment by xcainiao** [comment]
嗯 对 群里那个樱花师傅用fuzzilli fuzz的
