### ISSUE TITLE
Are you willing to make the dataset public? And some questions about paper.

### ISSUE THREAD

**Issue by ty5491003** [SoftSec-KAIST/CodeAlchemist#6]
Firstly, thanks for your work, it's amazing.

And as the title says, It is helpful if you can make the dataset public. I mean, the **63,692 js seed files** you mentioned in your paper.

Thank you in advance!

**Comment by ty5491003** [comment]
@DaramG Hello, I just finished reading your paper, it's great!  I have some questions about it and I wish you can help me. My questions as follows:

1. What's the mean of **`top-level statement`**? 
Based on my understanding, both a non loop statement and a loop(including head and body) can be deemed as a top-level statement, right? Look a example:
```javascript
var n = 42;
var arr = new Array(0x100);
for (let i = 0; i < n; i++) 
{
    arr[i] = n;
    arr[n] = i;
}
var b = 1;
```
I think the number of top-level statement for this example is `4`, am i right? If not, please tell me why.


2. In the section `§VI-C Choosing Parameters`, how do you determine if crash is unique? According to personal experience or manually analyse?

3. In the section `§VI-D (2)Comparison on the Latest JS Engines`, you mentioned that:
> Table II presents the number of unique crashes each engine found after 2,112 CPU hours of fuzzing.

There are 3 fuzzers and 4 engines, the `2,112 CPU hours` means using a fuzzer to fuzz a engine need to spend 2,112 CPU hours(actually 24 hours)?

4. In the timing comparison of the two fuzzers, will their different implementations affect the final experimental results? For example, there are two fuzzers named A and B respectively, A's fuzzing algorithm is better than B actually, but because of the implement of B is better than A, the final evaluation result of A is inferior to B. So **how can we compare the algorithms of two fuzzers fairly**?
This is a confusion of mine and I'd like to hear your opinion.

**Looking forward you reply, thank you in advance.**

**Comment by DaramG** [comment]
Thanks for your interest and questions!

1. Dataset
We are very sorry to say that we don't have plan to make dataset public.

2. What's the mean of `top-level statement`?
Typically, program is a collection of statements and statements are defined recursively. So, some word is required to express the very first statement of program and it was `top-level statement`.  In your example, the number of `top-level statement` is 4 as you think.

3. How to determine unique crash in the section `§VI-C (2) Choosing Parameters`?
We first triaged crashes by their call stack and manually analyzed them.

4. CPU hours in `§VI-D (2)Comparison on the Latest JS Engines`
Yes, as you said, we spent `2,112 CPU hours` (actually 24 hours in our environment) to run a fuzzer against a target engine.

5. How to compare fuzzing algorithms of two fuzzers fairly?
It's hard problem but I just write my thought here.
To compare only fuzzing algorithms, we should make everything same except the fuzzing algorithms. However, in case of comparing fuzzing algorithms of two fuzzers, it's very hard to make everything same. So, to prove fuzzing algorithms is good, papers usually evaluate two versions of their fuzzer, with and without the new fuzzing algorithm which they are willing to show. For example, in our paper, we evaluated two versions of CodeAlchemist with and without assembly constraints.

**Comment by ty5491003** [comment]
@DaramG I get it, thanks for your reply.

And i have a little advise about  the `readme.md`, which says:
> Installation for dotnet depends on OS version, so please refer this link.

When i enter this link and choose Ubuntu18.04 x64, the default version of .Net Core SDK is `3.1`, then I installed 3.1 version as the page says.

However, When I run the command `dotnet bin/Main.dll rewrite`, i got an error:
```bash
(python2) ty@ty-virtual-machine:~/CodeAlchemist$ dotnet bin/Main.dll rewrite /home/ty/CodeAlchemist/conf/Chakra.conf 
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
  - The following frameworks were found:
      3.1.0 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=2.1.0&arch=x64&rid=ubuntu.18.04-x64
```

Then, I uninstall .NET Core 3.1 and install .NET Core 2.1, it worked. I have to say that it took me some unnecessary time because of the missing info of default version.

So I think you can add a description of .NET Core version in Ubuntu18.04  to `readme.md`. 

It's just a little advise, but i think it can make this repo more perfect.

**Comment by DaramG** [comment]
Thanks for your suggestion and I will update in the near future!
