### ISSUE TITLE
help

### ISSUE THREAD

**Issue by bird8693** [SoftSec-KAIST/CodeAlchemist#7]
I want to test some other softwares, what can I do to make CodeAlchemist support them? like:
1）https://github.com/Moddable-OpenSource/moddable
2）https://github.com/jerryscript-project/jerryscript
3） https://github.com/pcmacdon/jsish

**Comment by bird8693** [comment]
@DaramG

**Comment by DaramG** [comment]
1. Add engine to `Engine` type in https://github.com/SoftSec-KAIST/CodeAlchemist/blob/master/src/Common/Conf.fs#L8
2. Update code for new engine type. Compiler will warn you where you should update.
3. Prepare conf files for each engine and run the fuzzer.
